# The purpose of this Dockerfile is to build a latest ubuntu image without any additional packages on the build stage.
# The image will be used to test installaction and configuration of packages via my scripts.
# We can use this docker to interactive test the scripts.

# To build this image use the following command:
# DOCKER_BUILDKIT=1 docker build --file test/docker/Dockerfile_dev_test_ubuntu_latest --tag docker_dev_test_ubuntu_latest .

# To run the image use the following command:
# docker run --rm -it docker_dev_test_ubuntu_latest

FROM ubuntu:latest AS builder

USER root

ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=Etc/UTC

RUN apt update
RUN apt upgrade -y

RUN apt install -y sudo
RUN apt install -y software-properties-common
RUN apt install -y tzdata

RUN ln -fs /usr/share/zoneinfo/Etc/UTC /etc/localtime
RUN dpkg-reconfigure --frontend noninteractive tzdata

RUN apt install -y shellcheck

# Copy the project files into the docker
COPY . /usr/local/src/personal-ubuntu-setup/

# Make the scripts executable
RUN chmod +x /usr/local/src/personal-ubuntu-setup/test/*.sh

# This docker is for manual testing, so no entrypoint is needed