# The purpose of this Dockerfile is to build a 24.04 LTS ubuntu image without any additional packages on the build stage.
# The image will be used to test installaction and configuration of packages via my scripts.

# To build this image use the following command:
# DOCKER_BUILDKIT=1 docker build --file test/docker/Dockerfile_ubuntu_2404 --tag docker_ubuntu_2404 .

# To run the image use the following command:
# docker run --rm docker_ubuntu_2404

FROM ubuntu:24.04 AS builder

USER root

ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=Etc/UTC

RUN apt update
RUN apt upgrade -y

RUN apt install -y shellcheck

# Copy the project files into the docker
COPY . /usr/local/src/personal-ubuntu-setup/

# Make the scripts executable
RUN chmod +x /usr/local/src/personal-ubuntu-setup/test/*.sh

# Run the script on the image startup via ENTRYPOINT
ENTRYPOINT ["/usr/local/src/personal-ubuntu-setup/test/test_local_main.sh"]