name: Ubuntu Developer CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Environment Preparation
      uses: actions/checkout@v2

    - name: Run tests as the developer
      run : |
        ./devenv_install.sh
        test/test_docker_main.sh

