name: Ubuntu 24.04 E2E CI

on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - main
      - development

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Environment Preparation
      uses: actions/checkout@v2

    - name: Checking disk usage
      run: df -h

    - name: Remove unnecessary files
      run : |
        sudo apt-get clean
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /usr/local/lib/android
        sudo rm -rf /opt/ghc

    - name: Symlink fonts to /mnt/runner/work
      run : |
        mkdir -p $HOME/.fonts
        sudo mkdir -p /mnt/runner/work/fonts
        sudo chown -R $USER:$USER /mnt/runner/
        ln -s /mnt/runner/work/fonts $HOME/.fonts

    - name: Symlink golang to /mnt/runner/work
      run : |
        mkdir -p $HOME/.go
        sudo mkdir -p /mnt/runner/work/go
        sudo chown -R $USER:$USER /mnt/runner/
        ln -s /mnt/runner/work/go $HOME/.go

    - name: Symlink python to /mnt/runner/work
      run : |
        mkdir -p $HOME/.python
        sudo mkdir -p /mnt/runner/work/python
        sudo chown -R $USER:$USER /mnt/runner/
        ln -s /mnt/runner/work/python $HOME/.python

    - name: Checking disk usage
      run: df -h

    - name: Run E2E tests
      run : |
        DOCKER_BUILDKIT=1 docker build --file test/docker/Dockerfile_e2e_ubuntu_2404 --tag docker_e2e_ubuntu_2404 .
        docker run --rm docker_e2e_ubuntu_2404

    - name: Checking disk usage
      run: df -h

